name: vaultwarden
values:
  applicationDependencies:
    - name: isNginxInstalled
      repository: gitlab.com/openlizz/applications/nginx
      shaRange: HEAD
    - name: isCertManagerInstalled
      repository: gitlab.com/openlizz/applications/cert-manager
      shaRange: HEAD
  clusterValues:
    - name: nginxName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/nginx" }}{{.Name}}{{ end }}{{ end }}'
    - name: nginxNamespace
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/nginx" }}{{.Configuration.Namespace}}{{ end }}{{ end }}'
    - name: certManagerName
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/cert-manager" }}{{.Name}}{{ end }}{{ end }}'
    - name: certManagerNamespace
      template: '{{ range .Applications }}{{ if eq .Configuration.Repository "gitlab.com/openlizz/applications/cert-manager" }}{{.Configuration.Namespace}}{{ end }}{{ end }}'
  passwords:
    - name: token
      length: 16
      numDigits: 5
      numSymbols: 0
      noUpper: false
      allowRepeat: false
dependencies:
  - {{ index . "isNginxInstalled" }}
  - {{ index . "isCertManagerInstalled" }}
dependsOn:
  - name: {{ index . "nginxName" }}
    namespace: {{ index . "nginxNamespace" }}
  - name: {{ index . "certManagerName" }}
    namespace: {{ index . "certManagerNamespace" }}
encryption:
  enabled: true
  inputPaths:
    - base/secret.yaml
