apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  values:
    ingress:
      hosts:
        - host: vaultwarden.kind.cluster
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: vaultwarden-cert
          hosts:
            - vaultwarden.kind.cluster
