apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: {{ index . "namespace" }}
spec:
  serviceAccountName: {{ index . "serviceAccountName" }}
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      version: "5.3.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    ingress:
      main:
        {{- if index . "isNginxInstalled" }}
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: vaultwarden.{{ index . "domain"}}
            paths:
              - path: "/"
                pathType: Prefix
        {{- else }}
        enable: false
        {{- end }}
        {{- if and (index . "isNginxInstalled") (index . "isCertManagerInstalled") }}
        tls:
          - secretName: vaultwarden-cert
            hosts:
              - vaultwarden.{{ index . "domain"}}
        {{- end }}
    persistence:
      config:
        enabled: true
        type: emptyDir
    env:
      DATA_FOLDER: "/data"
      SIGNUPS_ALLOWED: false
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-admin-token
            key: token
