apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  serviceAccountName: vaultwarden
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: vaultwarden
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
    # persistence:
    #   enabled: true
    # env:
    #   SIGNUPS_ALLOWED: false
    #   ADMIN_TOKEN:
    #     valueFrom:
    #       secretKeyRef:
    #         name: vaultwarden-admin-token
    #         key: token
