apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bjw-s-helm-charts
  namespace: {{index . "namespace"}}
spec:
  interval: 30m
  url: https://bjw-s.github.io/helm-charts/
